"""creat first table

Revision ID: 91ae309aaf1f
Revises: 
Create Date: 2024-03-22 10:50:44.376006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91ae309aaf1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('activeCode', sa.String(length=255), nullable=False, comment='验证码'),
    sa.Column('activeValidityPeriod', sa.DateTime(), nullable=False, comment='验证码有效期'),
    sa.Column('createTime', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('deleted', sa.SmallInteger(), server_default='0', nullable=False, comment='删除:删除0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True, comment='用户名称'),
    sa.Column('username', sa.String(length=20), nullable=False, comment='用户账号'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='邮箱'),
    sa.Column('sex', sa.SmallInteger(), server_default='1', nullable=True, comment='性别:男1,女0'),
    sa.Column('disabled', sa.SmallInteger(), server_default='1', nullable=False, comment='禁用用户:启动1,禁用0'),
    sa.Column('createTime', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('loginNumber', sa.Integer(), nullable=True, comment='登录次数'),
    sa.Column('clientHost', sa.String(length=20), nullable=True, comment='客户端HOST'),
    sa.Column('lastLoginTime', sa.DateTime(), nullable=True, comment='最后一次登录时间'),
    sa.Column('deleted', sa.SmallInteger(), server_default='0', nullable=False, comment='删除:删除0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='emailUnique'),
    sa.UniqueConstraint('username', name='usernameUnique')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('active')
    # ### end Alembic commands ###
